package simulacion;

import ast.Bloque;
import ast.CycleDetectedException;
import ast.DuplicateNodeException;
import ast.Nodo;
import compilador.Lexer;
import compilador.Parser;
import compilador.UnknownTokenException;
import compilador.WrongSyntaxException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    private final Canvas canvas;

    public Interfaz() {
        initComponents();
        this.setTitle("Precedencias");
        canvas = new Canvas();
        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
                canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 500, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
                canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 476, Short.MAX_VALUE)
        );

        canvasScrollPane.setViewportView(canvas);
        pack();
    }

    private void procesarListaNodos(ArrayList<Nodo> nodos) {
        try {
            for (Nodo i : nodos) {
                i.detectarCiclos();
                i.removerAtajos();
                i.resolverInderecciones();
                i.asignarNivel();
            }
            canvas.setNodos(nodos);
            canvas.ubicarNodos();
            canvas.repaint();
        } catch (CycleDetectedException ex) {
            JOptionPane.showMessageDialog(this, "Error: ciclo detectado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        codigoScrollPane = new javax.swing.JScrollPane();
        areaCodigo = new javax.swing.JTextArea();
        botonCompilar = new javax.swing.JButton();
        canvasScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        areaCodigo.setColumns(20);
        areaCodigo.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        areaCodigo.setRows(5);
        areaCodigo.setText("cobegin\n  begin\n    cobegin\n      begin\n        cobegin\n          A; B\n        coend\n        C\n      end\n      begin\n        cobegin\n          D; E\n        coend\n        F\n      end\n    coend\n    G; V(a); H\n  end\n  begin\n    J; P(a); I; K; L; M\n  end\ncoend");
        areaCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        codigoScrollPane.setViewportView(areaCodigo);

        botonCompilar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        botonCompilar.setText("Compilar");
        botonCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompilarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCompilar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(codigoScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCompilar))
        );

        canvasScrollPane.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(canvasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompilarActionPerformed
        String codigo = areaCodigo.getText().replaceAll("\t", "    ");
        try {
            Parser p = new Parser(new Lexer(codigo));
            p.getAst().asignarPrecedencias();
            procesarListaNodos(Bloque.listarNodos());
        } catch (UnknownTokenException ex) {
            JOptionPane.showMessageDialog(this, "Error: lexema desconocido");
        } catch (WrongSyntaxException ex) {
            JOptionPane.showMessageDialog(this, "Error: sintaxis incorrecta");
        } catch (DuplicateNodeException ex) {
            JOptionPane.showMessageDialog(this, "Error: nodo duplicado");
        }
    }//GEN-LAST:event_botonCompilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaCodigo;
    private javax.swing.JButton botonCompilar;
    private javax.swing.JScrollPane canvasScrollPane;
    private javax.swing.JScrollPane codigoScrollPane;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
